### ISSUE TITLE
Including "and" in text search returns 0 results

### ISSUE THREAD

**Issue by dionmcm** [AuDigitalHealth/medserve#18]
*Originally reported by* **John Grimes (Bitbucket: [j0hngr1mes](https://bitbucket.org/j0hngr1mes), GitHub: Unknown)**

----------------------------------------

Including "and" in text search returns 0 results, even if it is present in the results.

* `cold flu` returns 713 results.
* `cold and flu` returns 0 results.

----------------------------------------
- Bitbucket: https://bitbucket.org/dion_mcmurtrie/medserve/issue/18

**Comment by johngrimes** [comment]
Awesome, thanks!
